services:
  vulnerable-app:
    build: ./vulnerable-app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - xss-network
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=vulnerable_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    restart: always

  attacker-server:
    build: ./attacker-server
    ports:
      - "8081:80"
    networks:
      - xss-network
    volumes:
      - ./attacker-server/logs:/var/www/html/logs
    restart: always

  db:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnerable_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xss-network
    restart: always
    command: --default-authentication-plugin=mysql_native_password

networks:
  xss-network:
    driver: bridge

volumes:
  db_data: 